/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

import common.function.dateTimeHandle;
import controller.consumeController;
import java.util.Date;
import javax.swing.JOptionPane;
import object.consumeObject;

/**
 *
 * @author Nguyen Van Tinh
 */
public class HomeLayout extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public HomeLayout() {
        initComponents();
        this.btnSetTodayMouseClicked(null);
        btnBack.setVisible(false);
    }
    
    final private int modeAddNew = 0,
            modeView = 1;
    private int modeCurrent = modeAddNew;
    private consumeController consumeControl = new consumeController();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCenter = new javax.swing.JPanel();
        pickerDate = new com.toedter.calendar.JDateChooser();
        lblDate = new javax.swing.JLabel();
        lblContent = new javax.swing.JLabel();
        txtContent = new javax.swing.JTextField();
        lblAmount = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnSetToday = new javax.swing.JButton();
        btnViewHistory = new javax.swing.JButton();
        lblUnit = new javax.swing.JLabel();
        panelTitle = new javax.swing.JPanel();
        lblTitleSite = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FUND MANAGEMENT");
        setBackground(new java.awt.Color(204, 255, 204));
        setName("mainFrame"); // NOI18N
        setResizable(false);

        panelCenter.setBackground(new java.awt.Color(204, 255, 204));
        panelCenter.setForeground(new java.awt.Color(51, 0, 153));

        pickerDate.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N

        lblDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDate.setText("Date:");

        lblContent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblContent.setText("Contents:");

        txtContent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtContent.setMinimumSize(new java.awt.Dimension(6, 25));
        txtContent.setPreferredSize(new java.awt.Dimension(6, 25));

        lblAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAmount.setText("Amount:");

        txtAmount.setMinimumSize(new java.awt.Dimension(6, 25));
        txtAmount.setPreferredSize(new java.awt.Dimension(6, 25));

        btnAdd.setBackground(new java.awt.Color(51, 255, 102));
        btnAdd.setFont(new java.awt.Font("DigifaceWide", 2, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(51, 0, 255));
        btnAdd.setText("Add");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(51, 255, 102));
        btnExit.setFont(new java.awt.Font("DigifaceWide", 2, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(51, 0, 255));
        btnExit.setText("Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        btnSetToday.setBackground(new java.awt.Color(51, 255, 102));
        btnSetToday.setFont(new java.awt.Font("DigifaceWide", 2, 18)); // NOI18N
        btnSetToday.setForeground(new java.awt.Color(51, 0, 255));
        btnSetToday.setText("Set today");
        btnSetToday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSetTodayMouseClicked(evt);
            }
        });

        btnViewHistory.setBackground(new java.awt.Color(51, 255, 102));
        btnViewHistory.setFont(new java.awt.Font("DigifaceWide", 2, 18)); // NOI18N
        btnViewHistory.setForeground(new java.awt.Color(51, 0, 255));
        btnViewHistory.setText("View history");
        btnViewHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewHistoryMouseClicked(evt);
            }
        });

        lblUnit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUnit.setText("unit: x 1000 VNĐ");

        panelTitle.setBackground(new java.awt.Color(204, 255, 204));

        lblTitleSite.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        lblTitleSite.setForeground(new java.awt.Color(51, 0, 153));
        lblTitleSite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleSite.setText("Add new consume");

        btnBack.setBackground(new java.awt.Color(51, 255, 102));
        btnBack.setFont(new java.awt.Font("DigifaceWide", 2, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(51, 0, 255));
        btnBack.setLabel("Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(lblTitleSite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        panelTitleLayout.setVerticalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleSite)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout panelCenterLayout = new javax.swing.GroupLayout(panelCenter);
        panelCenter.setLayout(panelCenterLayout);
        panelCenterLayout.setHorizontalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCenterLayout.createSequentialGroup()
                .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCenterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelCenterLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAmount)
                            .addComponent(lblContent)
                            .addComponent(lblDate))
                        .addGap(18, 18, 18)
                        .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCenterLayout.createSequentialGroup()
                                .addComponent(pickerDate, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(btnSetToday, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtContent, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelCenterLayout.createSequentialGroup()
                                .addComponent(btnViewHistory)
                                .addGap(77, 77, 77)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCenterLayout.createSequentialGroup()
                                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblUnit)))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelCenterLayout.setVerticalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCenterLayout.createSequentialGroup()
                .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDate)
                    .addComponent(pickerDate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSetToday, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnit))
                .addGap(18, 18, 18)
                .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContent)
                    .addComponent(txtContent, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCenter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        //String date = pickerDate.getDate();
        try{
            String result = consumeControl.addConsume(pickerDate.getDate(), txtAmount.getText(), txtContent.getText());
            if (result.equals("")){
                JOptionPane.showMessageDialog(null, "Success!");
            }else{
                JOptionPane.showMessageDialog(null, result);
            }
            System.out.println(result);
        }catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnSetTodayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSetTodayMouseClicked
        // TODO add your handling code here:
        Date date = new Date();
        pickerDate.setDate(date);
    }//GEN-LAST:event_btnSetTodayMouseClicked

    private void btnViewHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewHistoryMouseClicked
        // TODO add your handling code here:
        //this.switchAddToHistory();
        consumeControl.closeConnect();
        this.setVisible(false);
        dispose();
        HistoryLayout.main(null);
    }//GEN-LAST:event_btnViewHistoryMouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        switch (this.modeCurrent){
            case modeView:
            break;
            case modeAddNew:
            break;
            default:
            break;
        }
    }//GEN-LAST:event_btnBackMouseClicked

    private void setInfo(consumeObject ob){
        pickerDate.setDate(ob.getDate());
        txtAmount.setText(Integer.toString(ob.getAmount()));
        txtContent.setText(ob.getContent());
    }
    /**
     * @param args the command line arguments
     */
    public static void run() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new HomeLayout().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSetToday;
    private javax.swing.JButton btnViewHistory;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblContent;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblTitleSite;
    private javax.swing.JLabel lblUnit;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelTitle;
    private com.toedter.calendar.JDateChooser pickerDate;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtContent;
    // End of variables declaration//GEN-END:variables
}
